version: "3.8"
services:
  common:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: bert-custom-training:1.0.0
    volumes:
      # hyperparameters.json to overwrite values defined in TRAIN_PARAM_JSONS files
      - ./config/hyperparameters.json:/opt/ml/input/config/hyperparameters.json

      # output model folder
      - ../model:/opt/ml/model

      # data folder
      - ../data:/opt/ml/data

      # cache
      - ../cache:/tmp/cache
    env_file: config/docker_env_file.env
    stdin_open: true
    tty: true

  download-cc100-ja:
    extends: common
    entrypoint: "src/pretrain_pipeline.sh download-cc100-ja"

  download-jawiki:
    extends: common
    entrypoint: "src/pretrain_pipeline.sh download-jawiki"
    tty: true

  build-dataset-cc100-ja:
    extends: common
    entrypoint: "src/pretrain_pipeline.sh build-dataset-cc100-ja"

  build-dataset-jawiki:
    extends: common
    entrypoint: "src/pretrain_pipeline.sh build-dataset-jawiki"

  train-tokenizer:
    extends: common
    entrypoint: "src/pretrain_pipeline.sh train-tokenizer"

  train-model-cc100-ja:
    extends: common
    runtime: nvidia
    environment:
      - DEVICE=cuda:0
      - TRAIN_PARAM_JSONS=src/config/train_params_bert_tiny_custom_cc100_ja.json
    entrypoint: "src/pretrain_pipeline.sh train-model"

  train-model-jawiki:
    extends: common
    runtime: nvidia
    environment:
      - DEVICE=cuda:0
      - TRAIN_PARAM_JSONS=src/config/train_params_bert_tiny_custom_jawiki.json
    entrypoint: "src/pretrain_pipeline.sh train-model"

  # train-model-domain: # one more pre-training step on domain of the down-stream task
  #   extends: common
  #   runtime: nvidia
  #   environment:
  #     - DEVICE=cuda:0
  #     - TRAIN_PARAM_JSONS=src/config/train_params_bert_tiny_custom_with_your_domain_text.json
  #   entrypoint: "src/pretrain_pipeline.sh train-model"

  all:
    extends: common
    runtime: nvidia
    environment:
      - DEVICE=cuda:0
      - TRAIN_PARAM_JSONS=src/config/train_params_bert_tiny_custom_cc100_ja.json:src/config/train_params_bert_tiny_custom_jawiki.json
    entrypoint: "src/pretrain_pipeline.sh all"
